app_key: "zal4owye5xcpk9w"
app_secret: <%= ENV["APP_SECRET"] %>
access_token: "6mr0tgc262tk60ny"
access_token_secret: <%= ENV["ACCESS_TOKEN_SECRET"] %>
user_id: "109659783"
access_type: "app_folder"

# SENSITIVE DATA